# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5beded84a5cf2c71a6f09689fa1230902718ab4ae1e13d653c0c1cd21407bfb1bf7a71fd66eaa0a777e2679ebe0227e5d613fc30b517e69a80a2af653b3f005e

test:
  secret_key_base: 1d4493b4369066054753187e3d78220387837cce77e88bfddd46410d4756e0ff7b5056cfb42853842f13661d7314f59f6f47b0647d90a1fcf39b85f2e01c38e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
